
export const detailObjOne = {
    id: 1,
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'REINFORCED WOOL UPPER',
    headline: 'Puddle Guard® On Duty',
    description: 'Soft and itch-free on the inside, the ZQ merino wool upper helps keep your feet dry thanks to our breathable, bio-based shield treated with fluorine-free water repellent coating.',
    imgStart: false,
    img: 'https://cdn.allbirds.com/image/upload/f_auto,q_auto,w_860/production/pageSectionBodyCard/en-US/images/4tw70cF572Md0jsus56PS2/1',
    alt: 'Car',
    dark: true,
    dark2: true,
    primary: true,
    darkText: false 
}

export const detailObjTwo = {
    id: 2,
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'SUGARCANE MIDSOLE',
    headline: 'Sweet Stability',
    description: 'Optimized for cushion, stability, and energy return, our dual-density SweetFoam™ midsole is made with the world’s first carbon negative green EVA.',
    imgStart: true,
    img: 'https://cdn.allbirds.com/image/upload/f_auto,q_auto,w_860/production/pageSectionBodyCard/en-US/images/3FZP8LUVaeSAnYu49zhkYB/1',
    alt: 'Piggybank',
    dark: false,
    dark2: true,
    primary: false,
    darkText: true, 
}

export const detailObjThree = {
    id: 3,
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'NATURAL RUBBER OUTSOLE',
    headline: 'Get A Grip',
    description: "The hardworking SweetFoam™ sole features FSC® Certified natural rubber treads for extra traction in wet conditions. And the flared, geometric design adds even more stability.",
    imgStart: false,
    img: 'https://cdn.allbirds.com/image/upload/f_auto,q_auto,w_860/production/pageSectionBodyCard/en-US/images/7mVFG7otji6Hh9fwDnCTDT/1',
    alt: 'Paper',
    dark: false,
    dark2: true,
    primary: false,
    darkText: true, 
}

export const detailObjFour = {
    id: 4,
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'HI-VIZ HIGHLIGHTS',
    headline: 'Safety First',
    description: "It’s important to stand out when you’re running in dark and stormy conditions. Reflective highlights around the shoe help pick up headlights so you can be seen on the streets.",
    imgStart: false,
    img: 'https://cdn.allbirds.com/image/upload/f_auto,q_auto,w_860/production/pageSectionBodyCard/en-US/images/4G2EZ1xlST7ntj3E7OWeEh/1',
    alt: 'Paper',
    dark: false,
    dark2: true,
    primary: false,
    darkText: true, 
}

export const detailObjFive = {
    id: 5,
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'CASTOR BEAN INSOLE',
    headline: 'Stride On',
    description: "Our removable castor bean sockliner emits less carbon than petroleum-based foam and is contoured to provide flexible, anatomical support.",
    imgStart: false,
    img: 'https://cdn.allbirds.com/image/upload/f_auto,q_auto,w_860/production/pageSectionBodyCard/en-US/images/6inJzHZB3XBDKZhYL3jrG1/1',
    alt: 'Paper',
    dark: false,
    dark2: true,
    primary: false,
    darkText: true, 
}

export const detailObjSix = {
    id: 6,
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '',
    headline: 'Tread Lighter',
    description: "Our Wool Dasher Mizzle is carbon neutral thanks to a combination of sustainable practices, like using natural materials and carbon credits. But before we balance the emissions, its footprint starts at 10.4 kg CO2e. Think of this measurement like a nutrition label for your closet.",
    imgStart: false,
    img: 'https://cdn.allbirds.com/image/upload/f_auto,q_auto,w_860/production/pageSectionBodyCard/en-US/images/x9o64OL4BHECtiIb2pSqw/1',
    alt: 'Carbon',
    dark: false,
    dark2: true,
    primary: false,
    darkText: true, 
}